export {default as AppointmentPage} from "./AppointmentPage"
export {default as Dashboard} from "./Dashboard"
export{default as Events} from "./EventsPage"
export {default as FeedbackPage} from "./FeedbackPage"
export{default as Fraud} from "./FraudPage"
export{default as News} from "./NewsPage"
export {default as Research} from "./ResearchPage"
export {default as Users} from "./UsersPages"
export {default as Sidebar} from "./Sidebar"
export {default as Careers} from "./CareersPage"
export {default as ServicesList} from "./Services"
export{default as Profile} from "./ProfilePage"
