export {default as Home} from "./Home"
export{default as Services} from "./Services"
export {default as Doctors} from  "./Doctors"
export {default as About} from "./About"
export{default as Feedback } from "./Feedback"
export{default as ReportFraud} from "./ReportFraud"
export{default as Appointment} from "./Appointment"